import 'package:educational_project/screens/routes/widgets/opacity_screen.dart';
import 'package:flutter/material.dart';

class WidgetRouteProvider extends ChangeNotifier {
  List<String> routes = [
    '/image',
    '/dio',
    '/datePicker',
    '/dismissible',
    '/animatediconScreen',
    '/slider',
    '/dataTable',
    '/selectableText',
    '/richText',
    '/aspectRatio',
    '/cupertinoIndicatorScreen',
    '/floatingActionButton',
    '/repaintBoundary',
    '/websocket',
    '/opacity',
    '/wrap',
    '/svg',
    '/table',
    '/pageView',
    '/sliverAppBar',
    '/fadeInImage',
    '/hero',
    '/clip',
    '/tooltip',
    '/fittedBox',
    '/absorbPointer',
    '/transform',
    '/backdropFilter',
    '/align',
    '/positioned',
    '/navigationBar',
    '/baseline',
    '/linearGradient',
    '/autocomplete',
    '/googleFonts',
    '/dropdownButton',
    '/badges',
    '/switchListTile',
    '/ratingBar',
    '/snackBar',
    '/gestureDetector',
    '/fontAwesome',
    '/animatedText',
    '/expansionPanelList',
    '/rotatedBox',
    '/slidable',
    '/physicalModel',
    '/gribview',
  ];
}
