// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgV7DrlRLw4CzEpiP7tp805F3ZIx5o46o',
    appId: '1:134395379318:web:b9670d4b6bf65266b06957',
    messagingSenderId: '134395379318',
    projectId: 'flutter-save',
    authDomain: 'flutter-save.firebaseapp.com',
    storageBucket: 'flutter-save.appspot.com',
    measurementId: 'G-B61BCBGBCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK58SWUpDZWnCx2PwS8lABZlpmkFDGQao',
    appId: '1:134395379318:android:4d7f452f97de4ec9b06957',
    messagingSenderId: '134395379318',
    projectId: 'flutter-save',
    storageBucket: 'flutter-save.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSjOLRe2zHX1SopIC6UWUDzgBMOWROclA',
    appId: '1:134395379318:ios:e15706ab6012db91b06957',
    messagingSenderId: '134395379318',
    projectId: 'flutter-save',
    storageBucket: 'flutter-save.appspot.com',
    iosBundleId: 'com.example.flutterSave',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSjOLRe2zHX1SopIC6UWUDzgBMOWROclA',
    appId: '1:134395379318:ios:5c44e1e5d9428342b06957',
    messagingSenderId: '134395379318',
    projectId: 'flutter-save',
    storageBucket: 'flutter-save.appspot.com',
    iosBundleId: 'com.example.flutterSave.RunnerTests',
  );
}
